// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWS01JVt6f2Nn0Nvgxi6yTv9XJTerrNaY',
    appId: '1:1092633819363:web:459c4613f4ff03f0f1add6',
    messagingSenderId: '1092633819363',
    projectId: 'whats-app-backend-flutter',
    authDomain: 'whats-app-backend-flutter.firebaseapp.com',
    storageBucket: 'whats-app-backend-flutter.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAP1Sjn0bXxc-ovzJCYDGyf5IMe6UhPKTw',
    appId: '1:1092633819363:android:f09b2e750a069e60f1add6',
    messagingSenderId: '1092633819363',
    projectId: 'whats-app-backend-flutter',
    storageBucket: 'whats-app-backend-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4G_Z2mE-BWziHmFfaqs_be8fSCg5ckXg',
    appId: '1:1092633819363:ios:c51f0d6c0f8b27e3f1add6',
    messagingSenderId: '1092633819363',
    projectId: 'whats-app-backend-flutter',
    storageBucket: 'whats-app-backend-flutter.appspot.com',
    iosClientId: '1092633819363-tbgoaqmr8an359g0ps8vtc07csngar33.apps.googleusercontent.com',
    iosBundleId: 'com.example.whatsappUi',
  );
}
